### ISSUE TITLE
fingerprint protection fails with badpadding

### ISSUE THREAD

**Issue by mirceanis** [uport-project/uport-android-sdk#30]
## Steps to reproduce:
* on a device with a fingerprint sensor
* run the [uport-android-signer](https://github.com/uport-project/uport-android-signer/tree/d0454811e5e4994a9e906adf59c5adbc7c33f885) demoapp
* tap `use fingerprint`, then tap `create a seed` then `sign a random string`
* approve the signature using your fingerprint
* The demoapp crashes with the following stacktrace:

```
    Process: me.uport.signer.demo, PID: 12608
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:448)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     Caused by: javax.crypto.BadPaddingException
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:515)
        at javax.crypto.Cipher.doFinal(Cipher.java:1741)
        at com.uport.sdk.signer.encryption.FingerprintAsymmetricProtection$decrypt$1.invoke(FingerprintAsymmetricProtection.kt:55)
        at com.uport.sdk.signer.encryption.FingerprintAsymmetricProtection$decrypt$1.invoke(FingerprintAsymmetricProtection.kt:20)
        at com.uport.sdk.signer.encryption.FingerprintAsymmetricProtection$showFingerprintDialog$1.onFingerprintSuccess(FingerprintAsymmetricProtection.kt:82)
        at com.uport.sdk.signer.encryption.FingerprintDialog$showSuccessText$1.onAnimationEnd(FingerprintDialog.kt:154)
        at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1122)
        at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1209)
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1449)
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
        at android.animation.AnimationHandler.-wrap2(Unknown Source:0)
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:976)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:722)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:964)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6501)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     Caused by: android.security.KeyStoreException: Invalid argument
        at android.security.KeyStore.getKeyStoreException(KeyStore.java:697)
        at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
        at javax.crypto.Cipher.doFinal(Cipher.java:1741) 
        at com.uport.sdk.signer.encryption.FingerprintAsymmetricProtection$decrypt$1.invoke(FingerprintAsymmetricProtection.kt:55) 
        at com.uport.sdk.signer.encryption.FingerprintAsymmetricProtection$decrypt$1.invoke(FingerprintAsymmetricProtection.kt:20) 
        at com.uport.sdk.signer.encryption.FingerprintAsymmetricProtection$showFingerprintDialog$1.onFingerprintSuccess(FingerprintAsymmetricProtection.kt:82) 
        at com.uport.sdk.signer.encryption.FingerprintDialog$showSuccessText$1.onAnimationEnd(FingerprintDialog.kt:154) 
        at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1122) 
        at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552) 
        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1209) 
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1449) 
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146) 
        at android.animation.AnimationHandler.-wrap2(Unknown Source:0) 
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54) 
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:976) 
        at android.view.Choreographer.doCallbacks(Choreographer.java:790) 
        at android.view.Choreographer.doFrame(Choreographer.java:722) 
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:964) 
        at android.os.Handler.handleCallback(Handler.java:790) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6501) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

**Comment by mirceanis** [comment]
fixed in [v0.2.1](https://github.com/uport-project/uport-android-sdk/releases/tag/v0.2.1)
